### ISSUE TITLE
Windows 版有问题

### ISSUE THREAD

**Issue by ZhReimu** [k0baya/memos-binary#3]
如图
![image](https://github.com/k0baya/memos-binary/assets/58155247/a312b4d7-6ad8-460f-9ca1-df2fdbd33dbb)
![image](https://github.com/k0baya/memos-binary/assets/58155247/255ce78b-d5f9-4eac-a0b0-9c92a308ab72)

**Comment by ZhReimu** [comment]
在 Windows 上手动编译了下，可以用了，新版本的 memos 把前端打包进了 exe，所以不需要 dist 目录了，得改下构建脚本

![image](https://github.com/k0baya/memos-binary/assets/58155247/0e6247dd-9dc9-487b-b9ac-98e7c75f5a68)

![image](https://github.com/k0baya/memos-binary/assets/58155247/0a3fffaa-e100-44fa-9193-092a440fb4ef)

**Comment by k0baya** [comment]
源仓库自0.22.0已经开始提供预构建二进制文件，所以暂且搁置了
